Documentation:
  Enabled: false

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - vendor/**/*
    - build/**/*
    - gemfiles/vendor/**/*

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - '*.gemspec'
    - spec/**/*.rb
    - '**/*.rake'
    - doc/**/*.rb

# We stay at 80 characters per line.
# See: https://rubystyle.guide/#max-line-length
Metrics/LineLength:
  Max: 80
