require:
  - rubocop-rspec
  - rubocop-rails

Rails:
  Enabled: true

Style/Documentation:
  Enabled: true

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - bin/**/*
    - vendor/**/*
    - build/**/*
    - gemfiles/**/*

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - '*.gemspec'
    - spec/**/*.rb
    - '**/*.rake'
    - doc/**/*.rb

# We stay at 80 characters per line.
# See: https://rubystyle.guide/#max-line-length
Layout/LineLength:
  Max: 80

# MFA is not yet enabled for our gems yet.
Gemspec/RequireMFA:
  Enabled: false

# We use memoized helpers all over the place to construct inputs and output
# which can be customized at nested contexts easily.
RSpec/MultipleMemoizedHelpers:
  Enabled: false
